[{if $sPaymentID == 'gc_giropay'}]
    [{if $oView->getActiveCurrencyName() == "EUR" && $oView->isSettingsSet($sPaymentID) == true}]
        [{$smarty.block.parent}]
    [{/if}]    
[{elseif $sPaymentID == "gc_directdebit"}]
    [{if $oView->getActiveCurrencyName() == "EUR" && $oView->isSettingsSet($sPaymentID) == true}]
        [{$smarty.block.parent}]
    [{/if}]   
[{elseif $sPaymentID == "gc_creditcard"}]
    [{if $oView->isSettingsSet($sPaymentID) == true}]
        [{$smarty.block.parent}]
    [{/if}]     
[{elseif $sPaymentID == "gc_ideal"}]
    [{if $oView->getActiveCurrencyName() == "EUR" && $oView->isSettingsSet($sPaymentID) == true}]
        [{$smarty.block.parent}]
    [{/if}]   
[{elseif $sPaymentID == "gc_eps"}]
    [{if $oView->getActiveCurrencyName() == "EUR" && $oView->isSettingsSet($sPaymentID) == true}]
        [{$smarty.block.parent}]
    [{/if}]   
[{elseif $sPaymentID == "gc_paydirekt"}]
    [{if $oView->getActiveCurrencyName() == "EUR" && $oView->isSettingsSet($sPaymentID) == true}]
        [{$smarty.block.parent}]
    [{/if}]   
[{elseif $sPaymentID == "gc_sofortuw"}]
    [{if $oView->getActiveCurrencyName() == "EUR" && $oView->isSettingsSet($sPaymentID) == true}]
        [{$smarty.block.parent}]
    [{/if}]   
[{else}]
    [{$smarty.block.parent}]
[{/if}]