[{if $sPaymentID == 'gc_giropay'}]
[{include file="mb_girocheckout_giropay.tpl"}]
[{elseif $sPaymentID == "gc_directdebit"}]
[{include file="mb_girocheckout_directdebit.tpl"}]
[{elseif $sPaymentID == "gc_creditcard"}]
[{include file="mb_girocheckout_creditcard.tpl"}]
[{elseif $sPaymentID == "gc_ideal"}]
[{include file="mb_girocheckout_ideal.tpl"}]
[{elseif $sPaymentID == "gc_eps"}]
[{include file="mb_girocheckout_eps.tpl"}]
[{elseif $sPaymentID == "gc_paydirekt"}]
[{include file="mb_girocheckout_paydirekt.tpl"}]
[{elseif $sPaymentID == "gc_sofortuw"}]
[{include file="mb_girocheckout_sofortuw.tpl"}]
[{else}]
[{$smarty.block.parent}]
[{/if}]